### ISSUE TITLE
100% CPU usage at all times

### ISSUE THREAD

**Issue by leobut** [DevilXD/TwitchDropsMiner#673]
Hello

First of all: big thanks to you guys for making this. I am a big fan of this tool, but I have one issue that I would like to report.

I am running this on my Macbook and it uses almost 100% of one CPU core at all times.
Right now it's just waiting for a campaign and minimized, but still at 97% usage.

Please have a look on how to reduce CPU usage while the program is basically just waiting for something to happen on twitch.

I have checked out the master branch directly and run the program using this: `nohup ./env/bin/python3 main.py &`
Running on python 3.13.1

Thanks and let me know if you have any more questions 😃

**Comment by DevilXD** [comment]
Hello,

Given that a Mac is supposedly an uncommon platform, that in itself could be the culprit. There's no easy way to debug this behavior, without me having like, access to the development environment setup on a Macbook, and even then, I'm not sure if I'd be able to find anything.

Python 3.13 could be the culprit as well, as the miner was extensively tested on versions 3.10 to 3.12 by now, but not really on 3.13 yet. There was some reports from 3.13.0, about a messed up Tkinter build being included and thus breaking the miner, and that being fixed in 3.13.1, but even then, I can only guarantee it works up to 3.12, as that's what I'm currently using for development and building locally. You can try changing to the latest 3.12 version to see if that helps.

Finally, the only `nohup` usage I know of, is to run something as detached from the SSH terminal, so that closing the session wouldn't kill the process via the HUNGUP signal. The interaction here could also cause issues. If you're running the miner locally, a simple `./env/bin/python3 main.py` should do. In the console window that pops up after launching the main miner file, you may see a traceback being printed, telling you that something went wrong. If there's nothing there and you're not interested in the console window at all, the proper way to run this thing without a console attached, is to use the `pythonw` executable instead of the `python` one.

**Comment by leobut** [comment]
Thank you very much for your very detailed response! 

So far I have only been able to try to downgrade the python version to 3.12, but still the same issue. I will keep you posted once I find the time to dive more into this topic.

Thanks, you're awesome!

**Comment by DevilXD** [comment]
Have you tried running it without `nohup`? The command would probably be: `./env/bin/python main.py`. If nothing is printed to the console, you can hide it by launching like this: `./env/bin/pythonw main.py`.

**Comment by leobut** [comment]
Hi, yes I did try that too but without success. Sorry for not mentioning it in my reply at first.

**Comment by leobut** [comment]
I had an idea and gave it a try. It's just a workaround, but it works for me and solves my issue at the moment 😄 

I wrapped the whole project into a docker container and run that locally on my mac. Uses only around 1.5% CPU 👍 
So when I want to change the settings of the tool, I run it on my localhost and once I have everything set up, I run it wrapped into docker. I can confirm that this works as I am seeing progress on Twitch 😉 

And for reference, here is my Dockerfile:

```
FROM python:3.13-slim

WORKDIR /twitch-drops-miner
COPY . /twitch-drops-miner

RUN apt-get update && apt-get install -y \
    gcc \
    clang \
    make \
    libcairo2-dev \
    pkg-config \
    libgirepository1.0-dev \
    gir1.2-gtk-3.0 \
    git \
    python3-tk \
    python3-pip \
    python3-venv \
    libayatana-appindicator3-1 \
    gir1.2-ayatanaappindicator3-0.1 \
    python3-dev \
    python3-cairo-dev \
    xvfb \
    && rm -rf /var/lib/apt/lists/*  # Clean up after installation

RUN ./setup_env.sh

CMD ["sh", "-c", "Xvfb :99 -screen 0 1920x1080x16 & export DISPLAY=:99 && ./env/bin/python3 main.py"]

```

Note: `xvfb` is needed for the container to emulate a display and run headless.

**Comment by DevilXD** [comment]
Hmm. Does this resolve this issue then? I'm not sure if I'm supposed to close it because you seem not to need help anymore, or keep it because it'll still use 100% CPU when ran on a Mac without Docker 🤔

**Comment by JourneyOver** [comment]
I'd honestly say keep it open for now just to see if someone else comes around with the same problem, since at the moment it's hard to fully know if this is just  a single user issue or a multi-user (anyone who was to run this on Mac) issue.

**Comment by leobut** [comment]
I recommend keeping this issue open to see if there are other Mac users with the same issue, but it's up to you of course 😃

**Comment by ZURICHRAN** [comment]
I'm also experiencing the same issue on my M2 MacBook.

The CPU usage stays at around 90–100% as long as the program is running.
I noticed something unusual in the GUI: the WebSocket status keeps rapidly switching between "Connected" and "Reconnecting" (e.g., "42/50" etc.). It looks like the script is constantly reconnecting in a very fast loop.

I'm currently running the program in a conda environment (Python 3.12). 
I'm suspecting that the frequent reconnect attempts may be causing the high CPU load.

Just leaving this comment to confirm that this issue affects multiple users.

**Comment by DevilXD** [comment]
@ZURICHRAN This is related to #871 instead, not this issue specifically.

**Comment by ZURICHRAN** [comment]
> [@ZURICHRAN](https://github.com/ZURICHRAN) This is related to [#871](https://github.com/DevilXD/TwitchDropsMiner/issues/871) instead, not this issue specifically.

Thanks for the clarification.
However, I’m still seeing the same symptom described here: the miner is using almost 100% of a single CPU core all the time.
Could this behavior be caused by the issue in #871?

**Comment by DevilXD** [comment]
If the websocket status is switching rapidly, then yes, it's possible. Each UI update has to redraw the window. For best results though, you'd have to compare it to a state from 2+ days ago, when #871 wasn't a thing yet.

Although, if I had to guess, looking back at all of this and beyond what I've already suggested above, the culprit could also be the way I've handled the Tkinter+asyncio combination in the miner. In case you're not versed enough in both of those: asyncio comes with an event loop, that handles all asynchronous operations within the app, while Tkinter comes with it's own event loop as well, that handles drawing and updating the UI window. Since only one loop can be the one driving the whole application, I had to "hack" the Tkinter one to follow the asyncio loop instead, and since it seemed to work quite nicely (at least on Windows), I just left it in. It's possible that the asyncio implementation on the Mac is done so in such a way, that it causes the loop to run too fast, leading to the UI update code consuming most of the CPU. This is the code responsible for this:

https://github.com/DevilXD/TwitchDropsMiner/blob/5f54c26f4af4be4d7de6394bbd7bc21b9ac3b1fd/gui.py#L2304-L2319

If you (or anyone else) would like to experiment with this, you can try changing that sleep from `0.05` to something higher. Just note that this delay defines the update rate for the GUI, so setting higher values will make the UI less responsive. Around `0.4` is probably the usability limit for an average user.
