### ISSUE TITLE
No progression towards drops - timer keeps resetting

### ISSUE THREAD

**Issue by Mexzter** [DevilXD/TwitchDropsMiner#749]
It seems that my progression keeps looping the last minute, in the below image for BF6 time timer will go down to 0:51:00 and then start again from 0:52:00.

<img width="436" height="324" alt="Image" src="https://github.com/user-attachments/assets/779b27ef-180c-4d05-baa0-9922b3057ba9" />

I have reset my password, reconnected my account couple of times and made sure my game accounts are linked. Re-downloaded the pre release from a couple days ago and deleted the cache file. My standard browser set in settings is chrome. There are no other tabs of twitch open except for the miner. Below is a dump from the miner.

[dump.zip](https://github.com/user-attachments/files/21810866/dump.zip)

**Comment by DevilXD** [comment]
Hello,

You're the second person contacting me about this. This leads me to believe there's some ongoing issue right now, either the miner stopped working, or Twitch has done something in regards to your account.

Please verify that you can progress the drop normally, via the browser.

By the way:

> My standard browser set in settings is chrome.

Not sure what you mean by this, as this isn't even a setting that exists in the miner.

**Comment by DarkViRnD** [comment]
Works well in the browser. Doesn't work with the miner.

**Comment by Kartemar** [comment]
Stopped working several hours ago. Drops works like a charm in browser.

**Comment by Killer99Man** [comment]
Same. In browser everyhink okay. In the script not okay.

**Comment by Mexzter** [comment]
> Hello,
> 
> You're the second person contacting me about this. This leads me to believe there's some ongoing issue right now, either the miner stopped working, or Twitch has done something in regards to your account.
> 
> Please verify that you can progress the drop normally, via the browser.
> 
> By the way:
> 
> > My standard browser set in settings is chrome.
> 
> Not sure what you mean by this, as this isn't even a setting that exists in the miner.

Yes I am able to progress in browser without an issue. I also found an old ticket #462 where someone mentioned the fork from Windows200000 which also has no success. 

What I meant with the default browser is when you click the login button it'll open up a twitch tab where you can enter your device code. In case this is to any means relevant to helping diagnose the issue.

**Comment by EnigmaWelcome** [comment]
Yes, Twitch changed something in its code and now progress has stopped working through Miner, but if you look through the browser, everything is fine and progress is going.

**Comment by kiroshu** [comment]
same

**Comment by Milky114** [comment]
I'm also experiencing the same issue.  When I start it up, a banner pops up and says that it's connected, but unencrypted.  Clicking on it doesn't do anything.  I've not noticed that in the past, so maybe it's related.

<img width="400" height="44" alt="Image" src="https://github.com/user-attachments/assets/55d0ee33-54e1-4633-aa5f-e755d1b2728c" />

**Comment by DevilXD** [comment]
No idea where you're getting that banner from, there's nothing in the miner that'd display something like that, anywhere.

My availability this weekend is quite spotty, but I'll try taking a look at it later today and/or tomorrow.

**Comment by Milky114** [comment]
> er

This is a larger screenshot of what I see when I first load into the webui.  The gray banner pops down at the top for about 3 seconds, then disappears.  I try to click on the `i` for more information, but nothing happens (in fact, clicking makes the bar go away faster).  Like say, I've never seen that before today.


<img width="1714" height="664" alt="Image" src="https://github.com/user-attachments/assets/ba64772b-1e96-489a-8bfe-c8924b876ebb" />

**Comment by DevilXD** [comment]
The current miner version has no dark mode support, and the window is dark on your screenshot. That means you are not using my version of the miner, so literally anything can pop up and happen for you. The miner from this repository has no such banner, nor any capabilities to display any banners in the first place.

Whatever that thing is, it's either due to you using a different version of the miner, or some other applications adds an overlay to the miner's window.

**Comment by leobut** [comment]
Hi I am having the same issue (not the banner issue, but no progression on drops).

I tried running while running the miner on windows and also on linux. Timer keeps resetting, no progression.
When I actually open a stream and have it running in my browser, I get progression.

From what I can see in my Twitch Drop history, this change must have happened sometime between now and 19 hours ago, as that's the last time I got a drop into my inventory.

**Comment by Hyrius** [comment]
@DevilXD https://discuss.dev.twitch.com/t/decommission-of-non-secure-websocket-connections-to-twitch-irc-servers/64142

**Comment by FadingToJosh** [comment]
> [@DevilXD](https://github.com/DevilXD) https://discuss.dev.twitch.com/t/decommission-of-non-secure-websocket-connections-to-twitch-irc-servers/64142

well that sucks, a ton of other tools used that as well.

**Comment by Hyrius** [comment]
I received this in an email a few days ago but initially thought it didn't apply, as I believed the Miner used secure WebSocket. 
Also, shouldn't this be only related to the IRC servers?

**Comment by leobut** [comment]
> I received this in an email a few days ago but initially thought it didn't apply, as I believed the Miner used secure WebSocket.

It does and I don't think this particular change affects the miner. Could be wrong though. 
See https://github.com/DevilXD/TwitchDropsMiner/blob/master/websocket.py#L153

**Comment by Hyrius** [comment]
> > I received this in an email a few days ago but initially thought it didn't apply, as I believed the Miner used secure WebSocket.
> 
> It does and I don't think this particular change affects the miner. Could be wrong though. See https://github.com/DevilXD/TwitchDropsMiner/blob/master/websocket.py#L153

Yeah, makes sense. But the date... if it's not related, it's definitely a big coincidence.

**Comment by Milky114** [comment]
> The current miner version has no dark mode support, and the window is dark on your screenshot. That means you are not using my version of the miner, so literally anything can pop up and happen for you. The miner from this repository has no such banner, nor any capabilities to display any banners in the first place.
> 
> Whatever that thing is, it's either due to you using a different version of the miner, or some other applications adds an overlay to the miner's window.

I'm using the app on Unraid.  When I clicked on the project page it brought me to this repository for some reason.  Sorry for the confusion.

**Comment by heartdeadz** [comment]
came here for  the same thing.
0 progress via the miner, but works just fine in browser.

hopefully you'll get it back working :D if possible! :D 

Thanks for the fantastic tool that's saved me hundreds of hours of mindless twitch streaming.

**Comment by DevilXD** [comment]
@Hyrius The article points to the chat websocket URL. The miner does use a Websocket connection, but not with the chat. Also, security is handled by `aiohttp`, the library responsible for establishing the connection, so it's very unlikely that change affects the miner in any way. Besides, mining progress comes from watching the stream, and that doesn't use Websocket. The Websocket connection is only responsible for receiving updates about channel status (going online or offline), and drop progression updates.

**Comment by MengYan6** [comment]
I have observed that the PlaybackAccessToken request parameters have changed.

**Comment by DevilXD** [comment]
I'm unable to confirm this, it looks the same as before on my end, including the non-changed operation hash.

**Comment by Killer99Man** [comment]
<img width="1209" height="62" alt="Image" src="https://github.com/user-attachments/assets/d626a612-6c86-49ba-b63a-44c54dc1bfaf" />

https://help.twitch.tv/s/?language=en_US

Does anyone know when this message appeared?

And is it related to script issues?

**Comment by DevilXD** [comment]
To be fair, this could be related, as the current miner version uses the mobile app client ID. There's a chance they'll fix this and the miner will start working again.

The smartbox client still has no access to campaigns, but inventory works, so besides having to manually start each campaign, the miner should be working there. Web client has integrity to it, so that's off limits. And mobile web is giving me auth issues after logging in, saying the token isn't valid after all. I guess we're sticking with the current client for now.

**Comment by leobut** [comment]
> To be fair, this could be related, as the current miner version uses the mobile app client ID. There's a chance they'll fix this and the miner will start working again.

To test this theory, I opened a stream open on the Twitch Android app and I got progress :S

**Comment by DevilXD** [comment]
Cool, but I have no way of reverse-engineering the android app, so it gets us nowhere. Twitch might've just killed this project for good.

I'd still recommend just waiting a few days to see how this turns out. From a few initial tests I did, nothing I do seems to be working anymore, so there's no immediate fix for this issue, unless someone else comes up with a different solution.

**Comment by yanzuchen04-coder** [comment]
Is anyone try to use other client id to drop？Is it useful?

**Comment by coodrag** [comment]
Sending the 'minute-watched' event by spade_url will increment watch minutes, as before.

**Comment by MengYan6** [comment]
> 与以前一样，通过 spade_url 发送“minute-watched”事件将增加观看分钟数。

Do you mean to change back to the previous mode?

**Comment by yanzuchen04-coder** [comment]
> Sending the 'minute-watched' event by spade_url will increment watch minutes, as before.

hi, Which client id is used when you add "Sending the 'minute-watched'" can use？

**Comment by Kitesszh** [comment]
same issue

**Comment by DevilXD** [comment]
Good news - I can confirm the previous way of mining, via "minute-watched" events being sent to Spade URL, does indeed progress the drops. Credit goes to @coodrag for pointing it out as a possible solution.

Ref commit from over a year ago: https://github.com/DevilXD/TwitchDropsMiner/commit/b47b2089c0a03c56aaede4560c7b99069a266729

I have a working solution, but some parts of the miner have changed ever since, especially when it comes to progress tracking. Right now, the timer only ends up counting down every 2nd or 3rd minute or so, staying frozen in-between. Because this lack of tangible feedback doesn't feel quite right to me, I'll need some more time before releasing the update. Hopefully today, tomorrow if not.

**Comment by DevilXD** [comment]
The old mining method has been reimplemented: https://github.com/DevilXD/TwitchDropsMiner/commit/826fe95f9c88fef984fb057adccc52ed1ba64792

You can grab the newest dev build, which includes this fix. I'll keep this issue open for a while, to prevent duplicate reports.

**Comment by DevilXD** [comment]
As I said, in case you've missed it, this issue will be kept open for a while, to avoid potential duplicates.

**Comment by LsHallo** [comment]
I've just tried the latest build.
Sadly it does not seem to work. Always resets to 3:52 remaining.
The initial 8min progress was from me watching in browser.
Here are 2 screenshots (6min apart):


<img width="1612" height="1006" alt="Image" src="https://github.com/user-attachments/assets/06f639c0-fbac-4156-9133-5cba3c803e78" />

<img width="1612" height="1013" alt="Image" src="https://github.com/user-attachments/assets/9ce8bf5c-95ab-4681-a962-72ab8ce67eda" />

Edit: Upon closer inspection it seems like just the campaign timer is buggy. The individual progress works. I just checked on the twitch page in browser.

**Comment by CoWinkKeyDinkInc** [comment]
Drops unlock and the progression bar works/switches over correctly. Thank you very much for the quick fix!

**Comment by DevilXD** [comment]
@LsHallo Hmm, cheers for catching that. Indeed, the drop timer works, but the campaign's one doesn't. I might've broke something while doing the update. Will take a closer look later today.

**Comment by Marcellse** [comment]
Encounter the same problem

**Comment by WilliamTrigos** [comment]
Same problem

**Comment by vS5g** [comment]
Can you add a switch to the next game or ignore games for 8 hours, 24 hours, and a week?

Right on the progress page.

**Comment by DevilXD** [comment]
@vS5g If this is a change suggestion for the miner, please open a separate issue for it. This issue is about the timer being constantly reset instead. Please keep it on-topic.

@Marcellse and @WilliamTrigos: This issue has already been resolved in the latest miner version, so if you're seeing this issue, please update to the newest version.

**Comment by Harudo** [comment]
Trojan was detected when i downloaded the windows Dev version.

**Comment by JourneyOver** [comment]
@Harudo it is false positive, I would suggest you look at literally every issue that has made any mention of virus/trojan and even https://github.com/DevilXD/TwitchDropsMiner#notes-about-the-windows-build and you would learn that they are false positives.

**Comment by kevinlf3** [comment]
Hi, I downloaded the last DEV release but doesn't working the progression of the drop. On the browser works fine but on the app doesn't work. I'm the only one who cannot make working? 

Example: I'm farming a Palia drop of 1hr and doesn't down of 00:58 min, resetting every 2 minutes.

EDIT: I deleted the cookies.jar and relogged and now is working!

Thanks!

**Comment by dangioffre** [comment]
Same issue. Works in browser but not in the app anymore.

**Comment by DevilXD** [comment]
@dangioffre The other user seems to have been able to solve their issue by deleting the cookie file, and relogging within the app. Have you tried that?

Also, make sure you're using the latest development version, as that's the only one where this is fixed.

**Comment by dangioffre** [comment]
> [@dangioffre](https://github.com/dangioffre) The other user seems to have been able to solve their issue by deleting the cookie file, and relogging within the app. Have you tried that?
> 
> Also, make sure you're using the latest development version, as that's the only one where this is fixed.

Yeah, I got it! Thanks. I also use it in unraid, but it's not using this repo its using one someone made "dungfu/twitch-drops-miner" that did not update the docker version, which was also my issue. So I ended up downloading the Windows app for now, and it's been working. Thank you for the work you do.

**Comment by JourneyOver** [comment]
> but it's not using this repo its using one someone made "dungfu/twitch-drops-miner" that did not update the docker version

Looks like the guy who made that isn't even using Devils base code anyways and instead uses Windows200000 base code on top of his own changes, so you'd probably run into some kind of other problems anyways as well at some point as Windows200000 base code is vastly different compared to Devils and he never really pulls in anything that devil does anymore.

It's one reason why I switched over to using devils base code a long time ago when I decided to do a docker fork.

**Comment by dangioffre** [comment]
> > but it's not using this repo its using one someone made "dungfu/twitch-drops-miner" that did not update the docker version
> 
> Looks like the guy who made that isn't even using Devils base code anyways and instead uses Windows200000 base code on top of his own changes, so you'd probably run into some kind of other problems anyways as well at some point as Windows200000 base code is vastly different compared to Devils and he never really pulls in anything that devil does anymore.
> 
> It's one reason why I switched over to using devils base code a long time ago when I decided to do a docker fork.

Yea,h using Devils, I already see many improvements!

**Comment by kevinlf3** [comment]
Hi, something it's not ok, the minner during all the night only farm 1 drop of 1hr and the other ones not, an its like 10hr or more since it complete the 1hr drop.

Maybe the progression it's not full fixed? And it's not because not have online streamers, it's Palia, a game with a lot of streamers online all the time.

Thanks!

**Comment by TheLovinator1** [comment]
> Hi, something it's not ok, the minner during all the night only farm 1 drop of 1hr and the other ones not, an its like 10hr or more since it complete the 1hr drop.
> 
> Maybe the progression it's not full fixed? And it's not because not have online streamers, it's Palia, a game with a lot of streamers online all the time.
> 
> Thanks!

<img width="1308" height="902" alt="Screenshot of Twitch Drops Miner v16.dev application window showing status connected to eight websockets, campaign progress for Palia Botanical Bliss Update at 96.5% with 37 minutes remaining, and current drop of 5x Gold Bars and Palcat Glasses at 89.4%. A list of Twitch channels for Palia is displayed with viewer counts, and the output log shows channel switching and drop claims." src="https://github.com/user-attachments/assets/3378ccc6-134a-49fb-8be4-b4f8033cfa2a" />

<img width="1287" height="260" alt="Screenshot of Twitch Drops campaign for Palia titled Botanical Bliss Update, ending on Monday September 8, 9:58 AM GMT+2. Five reward items are shown with progress bars: 5x Celebration Cake (completed), 5x Gold Bars (89% of 6 hours), Palcat Glasses (89% of 6 hours), 2x Greenhome Clay Pot, and 3x Lucky Coin." src="https://github.com/user-attachments/assets/4fe50efa-3614-4a15-a129-4fbe40d9ed8f" />

Works for me ™️

**Comment by kevinlf3** [comment]
Why you have the v16.dev and I have the v16.dev82dfe95?

<img width="307" height="37" alt="Image" src="https://github.com/user-attachments/assets/9d93471d-1c4e-4f77-93dc-d2b5d54d8830" />

**Comment by kevinlf3** [comment]
> > Hi, something it's not ok, the minner during all the night only farm 1 drop of 1hr and the other ones not, an its like 10hr or more since it complete the 1hr drop.
> > Maybe the progression it's not full fixed? And it's not because not have online streamers, it's Palia, a game with a lot of streamers online all the time.
> > Thanks!
> 
> <img alt="Screenshot of Twitch Drops Miner v16.dev application window showing status connected to eight websockets, campaign progress for Palia Botanical Bliss Update at 96.5% with 37 minutes remaining, and current drop of 5x Gold Bars and Palcat Glasses at 89.4%. A list of Twitch channels for Palia is displayed with viewer counts, and the output log shows channel switching and drop claims." width="1308" height="902" src="https://private-user-images.githubusercontent.com/4153203/479934101-3378ccc6-134a-49fb-8be4-b4f8033cfa2a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU2ODY3NzIsIm5iZiI6MTc1NTY4NjQ3MiwicGF0aCI6Ii80MTUzMjAzLzQ3OTkzNDEwMS0zMzc4Y2NjNi0xMzRhLTQ5ZmItOGJlNC1iNGY4MDMzY2ZhMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA4MjBUMTA0MTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVjZTFjMWFkMTBhNmU5NjcyMjA3NTZjYjAzNmMyOTRiNWZiOWY2ZmRmN2EwNjE3NTI2NTg5YTM0NGQyZDAxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.O5CzUH9qJ458uYtfoJQzRnFkzb0Juix2NZQc1VbA9X0"> <img alt="Screenshot of Twitch Drops campaign for Palia titled Botanical Bliss Update, ending on Monday September 8, 9:58 AM GMT+2. Five reward items are shown with progress bars: 5x Celebration Cake (completed), 5x Gold Bars (89% of 6 hours), Palcat Glasses (89% of 6 hours), 2x Greenhome Clay Pot, and 3x Lucky Coin." width="1287" height="260" src="https://private-user-images.githubusercontent.com/4153203/479934845-4fe50efa-3614-4a15-a129-4fbe40d9ed8f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU2ODY3NzIsIm5iZiI6MTc1NTY4NjQ3MiwicGF0aCI6Ii80MTUzMjAzLzQ3OTkzNDg0NS00ZmU1MGVmYS0zNjE0LTRhMTUtYTEyOS00ZmJlNDBkOWVkOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA4MjBUMTA0MTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTljNGYxMjQ3YjI4MDBiZDFiN2Q0MmY4ZWZjZjE1YzczMjFkMTQzM2VhNDNlMmVmZWZhODg3ODNmNjgxZTJkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.46zYTpAjje5-AhBtRMFl6ejT1e5pUziLgXMFLtPaKMc">
> Works for me ™️

Why you have the v16.dev and I have the v16.dev82dfe95?

<img width="307" height="37" alt="Image" src="https://github.com/user-attachments/assets/9d93471d-1c4e-4f77-93dc-d2b5d54d8830" />


My drop progression still not working, If I open the stream i'm minning on the browser, the progression is working but only with the app opened not working...

**Comment by DevilXD** [comment]
> Why you have the v16.dev and I have the v16.dev82dfe95?

Running from source does not add the short commit SHA to the version string. It's actually something I wanted to add to the source version as well at some point, just haven't gotten around to figuring out how to do that yet.

@kevinlf3 Please run the miner with the `--dump` option, and post the resulting `dump.dat` file here, which should appear in the miner's folder. You may need to zip it, for Github to allow the upload.

**Comment by manalshaikh** [comment]
Same issue. Tried building it myself and the issue remains. 
Also tried release variant but same. 
Both on Linux(Debian Trixie) and Windows 11.

**Comment by JourneyOver** [comment]
I'd suggest you provide your dump as well @manalshaikh as devil is more than likely going to ask for it.

**Comment by kevinlf3** [comment]
> > Why you have the v16.dev and I have the v16.dev82dfe95?
> 
> Running from source does not add the short commit SHA to the version string. It's actually something I wanted to add to the source version as well at some point, just haven't gotten around to figuring out how to do that yet.
> 
> [@kevinlf3](https://github.com/kevinlf3) Please run the miner with the `--dump` option, and post the resulting `dump.dat` file here, which should appear in the miner's folder. You may need to zip it, for Github to allow the upload.

Here is the dump! @DevilXD 

[dump.zip](https://github.com/user-attachments/files/21897004/dump.zip)

**Comment by manalshaikh** [comment]
> I'd suggest you provide your dump as well [@manalshaikh](https://github.com/manalshaikh) as devil is more than likely going to ask for it.

Hi. How do I do it? I compiled it and it appeared into `dist/`. Should I cmd prompt and do --dump along with its executable.

**Comment by DevilXD** [comment]
That's one of the ways of doing it, yes. On Windows, one usually just makes a shortcut with the argument added. Not sure if shortcuts are possible in your case, but a command line way should also work.

**Comment by Drmtrue** [comment]
Not mining for me too. Attaching dump file @DevilXD 

[dump.zip](https://github.com/user-attachments/files/21898749/dump.zip)

**Comment by manalshaikh** [comment]
[dump.zip](https://github.com/user-attachments/files/21898818/dump.zip)

Here you go. 
It should be noted that when i opened the program with dump param, it opened for a few second and then closed itself. I believe that might be its native behavior of debugging than just elevated verbosity.

Anyways. 
Hope this is fixed soon. Thanks!

**Comment by adressepoubelleaspam-ship-it** [comment]
I had the same issue: the miner always reset the timer and I never got the drop. I tried to get the new version, but Windows Defender says there’s a trojan inside.
I forced it to launch and it works, but I still get a trojan on my pc...

**Comment by DevilXD** [comment]
Hmmmmm. That's quite funny tbh. Twitch reports 413% progress on a drop.

<img width="422" height="247" alt="Image" src="https://github.com/user-attachments/assets/7ff2b921-e643-476f-9f20-c1ddb7d0decd" />

No idea how that has happened, but the other two dumps look quite normal. Not entirely sure what the issue might still be.

> I still get a trojan on my pc...

You can just silence the antivirus if it annoys you. Adding the executable to exceptions should do it.

I've noticed something strange. The CI version of the miner is detected even by my antivirus now, while the locally built version isn't. Besides the build process being slightly different (Github Actions vs local PC), the current CI uses Python 3.10, while I do the dev work on Python 3.12. I can try upgrading the minimum Python version, as long as that'd help, but the only way to find this out is to change the CI. I need to think about it.

Can anyone still experiencing issues try this thing out? This is a locally built version of the current latest version of the miner.

[TDM.v16.826fe95.zip](https://github.com/user-attachments/files/21901983/TDM.v16.826fe95.zip)

**Comment by adressepoubelleaspam-ship-it** [comment]
> Hmmmmm. That's quite funny tbh. Twitch reports 413% progress on a drop.
> 
> <img alt="Image" width="422" height="247" src="https://private-user-images.githubusercontent.com/4180725/480112701-7ff2b921-e643-476f-9f20-c1ddb7d0decd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU3MTAwNTQsIm5iZiI6MTc1NTcwOTc1NCwicGF0aCI6Ii80MTgwNzI1LzQ4MDExMjcwMS03ZmYyYjkyMS1lNjQzLTQ3NmYtOWYyMC1jMWRkYjdkMGRlY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA4MjBUMTcwOTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU3MzQ3ZTc5Zjg4MWYyMWE0NjI4NTEzN2YzN2EzMDc2NmNkMjJjODdkZWQ5Mjg2ZTVjNzZkNGMwZmMzYjliOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yZwv3Gjv-GBgwsibhjPaEUI1SXzzoKY8tWZ27qKg7DA">
> No idea how that has happened, but the other two dumps look quite normal. Not entirely sure what the issue might still be.
> 
> > I still get a trojan on my pc...
> 
> You can just silence the antivirus if it annoys you. Adding the executable to exceptions should do it.
> 
> I've noticed something strange. The CI version of the miner is detected even by my antivirus now, while the locally built version isn't. Besides the build process being slightly different (Github Actions vs local PC), the current CI uses Python 3.10, while I do the dev work on Python 3.12. I can try upgrading the minimum Python version, as long as that'd help, but the only way to find this out is to change the CI. I need to think about it.
> 
> Can anyone still experiencing issues try this thing out? This is a locally built version of the current latest version of the miner.
> 
> [TDM.v16.826fe95.zip](https://github.com/user-attachments/files/21901983/TDM.v16.826fe95.zip)

I prefer not to have a Trojan on my PC :( I didn't have any with version 16.dev.a.26b359

**Comment by kevinlf3** [comment]
> 
> Can anyone still experiencing issues try this thing out? This is a locally built version of the current latest version of the miner.
> 
> [TDM.v16.826fe95.zip](https://github.com/user-attachments/files/21901983/TDM.v16.826fe95.zip)

This one is not working for me, same issue, 1 minute drop farming and resetting @DevilXD

**Comment by DevilXD** [comment]
@adressepoubelleaspam-ship-it This application is not a trojan. I have no idea what can be causing this, outside of the usual joys of dealing with PyInstaller and it's detections. This is the entire diff between a26b359 and current master, for anyone wanted to look into it: https://github.com/DevilXD/TwitchDropsMiner/compare/a26b3596877776e78f26888fac896fceb3b58c21..master

@kevinlf3 I really have no idea then. Twitch was reporting some bogus progress being made on the drops in your case, which may have contributed to it not working, but that's about it. Everything works on my side with no issues, so it's impossible for me to figure out what it may be in your case.

**Comment by kevinlf3** [comment]
Ok, well, I will wait for another update... Thanks! @DevilXD

**Comment by dangioffre** [comment]
I've been using v16.dev.826fe95 the Windows app. It has been working perfectly. 

My Windows does scan it as a virus, but it is safe.

@DevilXD @adressepoubelleaspam-ship-it

**Comment by adressepoubelleaspam-ship-it** [comment]
@DevilXD thx for your work <3

**Comment by manalshaikh** [comment]
Okay. I got it working. It wasn't straight forward, but I got it. 

@DevilXD 
> Can anyone still experiencing issues try this thing out? This is a locally built version of the current latest version of the miner.
> 
> [TDM.v16.826fe95.zip](https://github.com/user-attachments/files/21901983/TDM.v16.826fe95.zip)

I tried running this and it kept saying it couldn't connect to Twitch servers and trying again in x seconds. Weirdly enough, I went to my DNS log and found "video-edge-3574d5.pdx01.abs.hls.ttvnw.net" was being blocked. Upon unblocking, it started mining. 
When I checked the progress, it was actually reflecting on twitch site. 

Now I thought the issue was fixed. So I went to old build and tried with that but every minute, starting from 11:59(duration not time), it would reset as soon as it reaches 13:00. This lead to me to believe the issue wasn't fixed. Since it was initially working on Devil's build, I decided to download the whole repo again and overrite it on top of old one(im too lazy to make 2 copies) and then compile it. Upon doing so, I have it working. I still have the old compiled exec with me but without having to relog, this issue is fixed. 

So the problem was either or both:
1) My DNS blocker blocking that ttv endpoint. 
2) Old version was somehow bugged. 

I'm more inclined towards 1st because others here in this issue said they compiled it from scratch and issue remained. 


I'm now going to test it on my Debian Trixie LXC where I usually run this(with wine, linux build is annoying and always not working) but as far as Windows is concerned it is fixed for me.
Hope this helps.

**Comment by manalshaikh** [comment]
It works on the Linux machine too. ^

**Comment by xXFerginatorXx** [comment]
@DevilXD Will a v16 be dropped in on the release section on https://github.com/DevilXD/TwitchDropsMiner/releases or are no new versions happening and to download the dev build? Just want to make sure I understand how to resolve the issue but I see the dev version is still listed as unstable so wanted to verify with you before I download.

EDIT: Apologies, did not see the v15 added note: ⚠️ NOT STABLE since February 2023, use the latest master / pre-release version for now, while waiting for v16 to come out ⚠️

All clear now

**Comment by EricInJP** [comment]
> 1. My DNS blocker blocking that ttv endpoint

Hi. Can you help me on this? I'm on Windows 11, how to unblock the DNS?

**Comment by Coreyo-git** [comment]
> 1. My DNS blocker blocking that ttv endpoint.

This wasn't the case for me, I checked dns records, the ttvnw endpoints weren't blocked, I monitored it for a while and the client had no blocked DNS requests while the issue still persisted.

**Comment by marcspc** [comment]
came because I didn't mined anything for a week, updated to last version from 2 hours ago, it's mining now, thanks

**Comment by manalshaikh** [comment]
It started happening again

**Comment by DevilXD** [comment]
To anyone still having issues - there was a fix released yesterday, that may help. Please ensure you're using the latest version, before reporting anything here.

All of the remaining issues with the miner getting stuck belong in #746. Since the progression is counted again, I'm closing this issue.
